image: atlassian/default-image:2

pipelines:

  branches:
    master:
      - step:
          name: Deploy to Production
          deployment: production
          script:
            - pipe: atlassian/sftp-deploy:0.5.8
              variables:
                USER: $SFTP_USERNAME
                SERVER: $SFTP_HOST
                REMOTE_PATH: '/dsixapi'
                PASSWORD: $SFTP_PASSWORD
#          script:
#            - pipe: atlassian/ftp-deploy:0.3.5
#              variables:
#                USER: $SFTP_USERNAME
#                PASSWORD: $SFTP_PASSWORD
#                SERVER: $SFTP_HOST
#                REMOTE_PATH: /
#                DELETE_FLAG: 'false' # Don't delete existing files
#                EXTRA_ARGS: "--exclude=.bitbucket/ --exclude=.git/ --exclude=bitbucket-pipelines.yml --exclude=.gitignore" # Ignore these
